# Generated by Django 4.2.2 on 2023-06-08 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_survey_description_alter_survey_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата старта - сегодня'),
        ),
    ]
