# Generated by Django 4.2.2 on 2023-06-08 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_survey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 8, 18, 4, 58, 745169, tzinfo=datetime.timezone.utc), verbose_name='Дата старта - сегодня'),
        ),
    ]
