# Generated by Django 4.2.2 on 2023-06-08 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_survey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 8, 18, 5, 8, 435470, tzinfo=datetime.timezone.utc), verbose_name='Дата старта - сегодня'),
        ),
    ]
