# Generated by Django 4.2.2 on 2023-06-08 18:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_survey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата старта - сегодня'),
        ),
    ]
