# Generated by Django 4.2.2 on 2023-06-10 16:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_survey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(verbose_name='Ответ пользователя'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.survey', verbose_name='Опрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='text',
            field=models.TextField(verbose_name='Текст варианта ответа'),
        ),
    ]
