# Generated by Django 4.2.2 on 2023-06-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_answer_answer_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Текст', 'Text'), ('Выбор одного варианта ответа', 'Choosing One'), ('Выбор нескольких вариантов', 'Choosing Multiple')], default='Текст', max_length=28, verbose_name='Тип ответа'),
        ),
    ]
