# Generated by Django 4.2.2 on 2023-06-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('Текст', 'Text'), ('Выбор одного варианта ответа', 'Choosing One'), ('Выбор нескольких вариантов ответов', 'Choosing Multiple')], default='Текст', max_length=34, verbose_name='Тип ответа'),
        ),
    ]
