# Generated by Django 4.2.2 on 2023-06-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_survey_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(verbose_name='Дата старта'),
        ),
    ]
