# Generated by Django 4.2.2 on 2023-06-15 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_survey_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата старта'),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('question', 'survey'), name='unique_answer'),
        ),
    ]
