# Generated by Django 4.2.2 on 2023-06-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_answer_user_id_alter_survey_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='answer',
            name='unique_answer',
        ),
    ]
