# Generated by Django 4.2.2 on 2023-06-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_answer_unique_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user_id',
            field=models.CharField(max_length=10),
        ),
    ]
